### ISSUE TITLE
Add Index .html file 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [rohank2502/INDIA-THE-POTENTIAL-SUPERPOWER#1]
Add a new file names `index.html` in repository

**Comment by rohank2502** [comment]
@gouriejagtap Will you like to do this

**Comment by GourieJagtap** [comment]
Shall I work on this issue?

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Shall I work on this issue?

Good to Go @GourieJagtap  Just Go with Creating Pr  !!
