### ISSUE TITLE
Redesign the Intro Box 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [rohank2502/INDIA-THE-POTENTIAL-SUPERPOWER#8]
![Screenshot 2021-05-29 102254](https://user-images.githubusercontent.com/76584243/120058352-d2754f80-c067-11eb-8e9c-1df042cbed15.png)

We can make few changes to the intro box like
The background of India and the whole box is in the same color this doesn't impact much we can change the background of any or or remove the bg of India box 

Animation is good just align it more to the right means after completing the whole animation the line will be centered to India 

And we can also blur the color of highlight this will look more attractive as we just want to highlight it ! 

Padding of the intro box can be made to 4 vmin as it is so much close to the edges it don't look good

**Comment by rohan-kulkarni-25** [comment]
@GourieJagtap  Will, you like to work on these changes ?

**Comment by GourieJagtap** [comment]
> @GourieJagtap Will, you like to work on these changes ?

Yes!

**Comment by GourieJagtap** [comment]
> ![Screenshot 2021-05-29 102254](https://user-images.githubusercontent.com/76584243/120058352-d2754f80-c067-11eb-8e9c-1df042cbed15.png)
> 
> We can make few changes to the intro box like
> The background of India and the whole box is in the same color this doesn't impact much we can change the background of any or or remove the bg of India box
> 
> Animation is good just align it more to the right means after completing the whole animation the line will be centered to India
> 
> And we can also blur the color of highlight this will look more attractive as we just want to highlight it !
> 
> Padding of the intro box can be made to 4 vmin as it is so much close to the edges it don't look good

Okay! I'll work on it .
